### ISSUE TITLE
Update to trefle 1.6 api?

### ISSUE THREAD

**Issue by gsmx** [zmasek/shamrock#11]
Hey Zlatko! Thanks for shamrock. Are going to update endpoints/ syntax to the new version? Shamrock ist broken since couple of days.

https://docs.trefle.io/blog/1-6-0-released/

**Comment by zmasek** [comment]
Hi, @gsmx. Short answer: yes. Long answer: some personal things happened so I am a bit late. I am aware that there was an update and am communicating with folks on the official Discord server so I will deliver probably tomorrow or the day after a new version with two new endpoints and one renamed and a new exception. I just need to test it first with a personal project to make sure it works. How urgent is this on your end?

EDIT: another subquestion. How important is it to you to keep a backwards compatibility?

**Comment by zmasek** [comment]
Hi, @gsmx ,
I released 0.0.2 to make calls to an old API version, but I'll work on releasing a new version today or tomorrow to switch to a new API version. The compatibility will likely break, but that's why 0.0.2 is there if needed.

**Comment by gsmx** [comment]
> EDIT: another subquestion. How important is it to you to keep a backwards compatibility?

I guess as trefle doesnt provide upgrade safety (until now) and just introduced versioning of apis, it should be okay to not support the old version, too.

**Comment by gsmx** [comment]
Works. Good job!

**Comment by zmasek** [comment]
I'll reopen it so I can track the new API connection. The tests are passing locally, so I'd need to go through the code once more before pushing. Then I guess it's some minor fixes. I expect to make the release in the coming days.

**Comment by zmasek** [comment]
Pushed the most of the work if you want to check it, @gsmx , but I'll close this for now.

**Comment by zmasek** [comment]
@gsmx released 0.1.0 on pypi. it's not backwards compatible so if you are working with it...
